/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard/admin/payments'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardAdminProductsIndexRouteImport } from './routes/dashboard/admin/products/index'
import { Route as DashboardAdminProductsNewRouteImport } from './routes/dashboard/admin/products/new'
import { Route as DashboardAdminProductsProductIdEditRouteImport } from './routes/dashboard/admin/products/$productId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminProductsIndexRoute =
  DashboardAdminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminProductsNewRoute =
  DashboardAdminProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminProductsProductIdEditRoute =
  DashboardAdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/admin/products/new': typeof DashboardAdminProductsNewRoute
  '/dashboard/admin/products/': typeof DashboardAdminProductsIndexRoute
  '/dashboard/admin/products/$productId/edit': typeof DashboardAdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/admin/products/new': typeof DashboardAdminProductsNewRoute
  '/dashboard/admin/products': typeof DashboardAdminProductsIndexRoute
  '/dashboard/admin/products/$productId/edit': typeof DashboardAdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/admin/products/new': typeof DashboardAdminProductsNewRoute
  '/dashboard/admin/products/': typeof DashboardAdminProductsIndexRoute
  '/dashboard/admin/products/$productId/edit': typeof DashboardAdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/$'
    | '/dashboard/admin'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/users'
    | '/dashboard/admin/'
    | '/dashboard/admin/products/new'
    | '/dashboard/admin/products/'
    | '/dashboard/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/dashboard/profile'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/users'
    | '/dashboard/admin'
    | '/dashboard/admin/products/new'
    | '/dashboard/admin/products'
    | '/dashboard/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/$'
    | '/dashboard/admin'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/users'
    | '/dashboard/admin/'
    | '/dashboard/admin/products/new'
    | '/dashboard/admin/products/'
    | '/dashboard/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/products/': {
      id: '/dashboard/admin/products/'
      path: '/products'
      fullPath: '/dashboard/admin/products/'
      preLoaderRoute: typeof DashboardAdminProductsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/products/new': {
      id: '/dashboard/admin/products/new'
      path: '/products/new'
      fullPath: '/dashboard/admin/products/new'
      preLoaderRoute: typeof DashboardAdminProductsNewRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/products/$productId/edit': {
      id: '/dashboard/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/dashboard/admin/products/$productId/edit'
      preLoaderRoute: typeof DashboardAdminProductsProductIdEditRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminProductsNewRoute: typeof DashboardAdminProductsNewRoute
  DashboardAdminProductsIndexRoute: typeof DashboardAdminProductsIndexRoute
  DashboardAdminProductsProductIdEditRoute: typeof DashboardAdminProductsProductIdEditRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminProductsNewRoute: DashboardAdminProductsNewRoute,
  DashboardAdminProductsIndexRoute: DashboardAdminProductsIndexRoute,
  DashboardAdminProductsProductIdEditRoute:
    DashboardAdminProductsProductIdEditRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
